# Generated by Django 4.2.1 on 2023-06-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_modules', '0003_doctor_email_doctor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='photo',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='doctor_rating',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(),
        ),
    ]
