# Generated by Django 4.2.1 on 2023-06-08 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_modules', '0005_patient_dob_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=200)),
                ('route', models.CharField(max_length=200)),
                ('instruction', models.CharField(max_length=200)),
                ('appointment', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospital_modules.appointment')),
            ],
        ),
    ]
