# Generated by Django 4.2.1 on 2023-08-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_modules', '0007_alter_doctor_rating_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.IntegerField()),
                ('receiver_id', models.IntegerField()),
                ('chat', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=200)),
            ],
        ),
    ]
