# Generated by Django 4.2.1 on 2023-08-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_modules', '0008_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='type',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
